variable "ecs_cluster_1_name" {}
variable "task_name" {}
variable "ecs_service_name" {}
variable "container_name" {}
variable "dockerhub_image" {}
variable "alb_root_target_group_arn" {}
variable "alb_about_route_target_group_arn" {}
variable "env_name" {}
variable "cidr_blocks" {}
variable "vpc_id" {}
