variable "env_name" {}
variable "subnet_id" {}
variable "target_type" {}
variable "protocol" {}
variable "ip_address_type" {}
variable "vpc_id" {}
variable "cidr_blocks" {}
variable "subnet_2_id" {}
variable "domain" {}
variable "ec2_instance_id" {}
