variable "web_server_firewall" {}
variable "env_name" {}
variable "subnet_id" {}
variable "target_type" {}
variable "protocol" {}
variable "ip_address_type" {}
variable "vpc_id" {}
variable "cidr_blocks" {}
variable "cert_arn" {}
